# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb-learn',
                'doc_host': 'https://asimsheikh.github.io',
                'git_url': 'https://github.com/asimsheikh/nb-learn',
                'lib_path': 'nb_learn'},
  'syms': {'nb_learn.core': {'nb_learn.core.foo': ('core.html#foo', 'nb_learn/core.py')}}}
